safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "周叶倩"
description: "一个前端初学者"
baseurl: ""
url: "http://himsel.me" # replace by your site's url
twitter_username: 周叶倩
github_username:  zhouywqian	 # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "周叶倩"
address: "中国，成都"
email: "zhouyq@wise2c.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
